# 异常处理

## try catch throw 和 throws
针对这种情况, Java总允许在方法的后面使用throws关键字对外声明该方法有可能发生异常, 这样调用者在调用方法时, 就明确地知道该方法有异常, 并且必须在程序中对异常进行处理, 否则编译无法通过. 
```java
public class Example {
 
    public static void main(String[] args) {
        
      try {
         int result = divide(4,2);
         System.out.println(result);
       } catch (Exception e) {
         e.printStackTrace();
       }
    }
    
    public static int divide(int x,int y) throws Exception {
      int result = x/y;
      return result;
   }
}
```